### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by Jon-Zbw** [zzpDapeng/speech_data_augment#1]
您好，您代码里数据增强有两种是直接生成了增强后的图片嘛？例如那个mask，这个更像是图片增强

**Comment by zzpDapeng** [comment]
> 您好，您代码里数据增强有两种是直接生成了增强后的图片嘛？例如那个mask，这个更像是图片增强

这些代码都是处理语音数据的。有两种是在特征（语谱图）上作数据增强，是SpecAugment里面的频率掩码和时间掩码，其他都是基于元是语音信号做的数据增强。不是图片增强

**Comment by Jon-Zbw** [comment]
感谢回复，如果想批量处理，需要加些什么代码？

**Comment by zzpDapeng** [comment]
> 感谢回复，如果想批量处理，需要加些什么代码？

已经更新了SpecAugment的批处理代码，对于其他增强算法（在语音信号上增强）可以使用循环进行批处理。

**Comment by Jon-Zbw** [comment]
我看您audio_path,还是单个wav文件，应该是一个包含若干wav文件的文件夹吧，然后把增强后一些的音频重新保存

**Comment by zzpDapeng** [comment]
> 我看您audio_path,还是单个wav文件，应该是一个包含若干wav文件的文件夹吧，然后把增强后一些的音频重新保存

这个项目是用于深度学习中语音相关模型的预处理，特征可直接作为模型的输入，不需要增强之后再转换成音频文件重新保存。而且好像也没有从特征逆向转化为音频的方法。我用一个音频文件提取出2维特征后，增加了一个batch维度，来模拟多个音频文件的特特征。

**Comment by Jon-Zbw** [comment]
ImportError: cannot import name 'read_wave_from_file' from 'utils' ，后面包括tensor_to_img  get_feature都不能导入，是不是utils版本问题，您那是？

**Comment by zzpDapeng** [comment]
> ImportError: cannot import name 'read_wave_from_file' from 'utils' ，后面包括tensor_to_img get_feature都不能导入，是不是utils版本问题，您那是？

项目的utils里有这两个函数。utils没其他版本

**Comment by Jon-Zbw** [comment]
不好意思，刚看到utils.py,哈哈，还有就是我看您其他的是重新save_wav() 保存为了新音频，就那两个语谱图直接模拟增强是吧？

**Comment by Jon-Zbw** [comment]
我以为是utils这个库，我还pip了一个.......好傻

**Comment by zzpDapeng** [comment]
> 不好意思，刚看到utils.py,哈哈，还有就是我看您其他的是重新save_wav() 保存为了新音频，就那两个语谱图直接模拟增强是吧？

我使用save_wav()保存音频只是为了听增强后的效果，并通过软件得到增强后语音信号图，实际深度学习项目中不需要保存音频，这里只是为了展示。
语谱图不能逆向还原成语音信号，所以不能保存成音频文件。在特征上增强后还是特征，可以直接用的，建议参考SpecAugment论文。

**Comment by Jon-Zbw** [comment]
能加个联系方式吗，我这生成的图有点滑稽。给您看下，哈啊哈

**Comment by zzpDapeng** [comment]
> 能加个联系方式吗，我这生成的图有点滑稽。给您看下，哈啊哈

更新了特征提取代码，现在的log mel特征更好点。
