### ISSUE TITLE
How to save as audio file after frequency mask

### ISSUE THREAD

**Issue by qq346249270** [zzpDapeng/speech_data_augment#2]
How to save as audio file after frequency mask

**Comment by zzpDapeng** [comment]
Frequency mask is operated on audio feature instead of raw audio. You can directly use the augmented feature in your training, and there is no need to save is as audio file. Besides，I don’t know how to convert a audio feature back to raw audio.

**Comment by qq346249270** [comment]
Thank you for your reply. I also have a sudden idea. If I can restore the masked spectrogram to the original data, will it be helpful for speech synthesis?In addition, I would like to ask whether the spectrogram without processing is significantly improved by directly replacing the spectrogram with the frequency mask




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzpDapeng/speech_data_augment"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午4:28
收件人:&nbsp;"zzpDapeng/speech_data_augment"<speech_data_augment@noreply.github.com&gt;;
抄送:&nbsp;"qiudafeng"<346249270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zzpDapeng/speech_data_augment] How to save as audio file after frequency mask (#2)





 
Frequency mask is operated on audio feature instead of raw audio. You can directly use the augmented feature in your training, and there is no need to save is as audio file. Besides，I don’t know how to convert a audio feature back to raw audio.

**Comment by liu-ioa** [comment]
@qq346249270 read this paper :SpecAugment: A Simple Data Augmentation Methodfor Automatic Speech Recognition
